insert into prompts (title, description, prompt_text, ai_tool, category_id, tags, use_case) values
('- Scope: root + meaningful modules', 'From awesome-chatgpt-prompts community collection', 'with stack-specific detection', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('CLAUDE.md"', 'From awesome-chatgpt-prompts community collection', 'the tool selects this skill as the best match', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- Generates or updates `CLAUDE.md` with verified', 'From awesome-chatgpt-prompts community collection', 'repo-derived content', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- A repo needs consistent', 'From awesome-chatgpt-prompts community collection', 'verified guidance for AI workflows', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- Repo docs: `README.md`', 'From awesome-chatgpt-prompts community collection', '`docs/*` (if present)', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('5. Generate root + module files', 'From awesome-chatgpt-prompts community collection', 'avoiding duplication via `@/CLAUDE.md`', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('targets', 'From awesome-chatgpt-prompts community collection', 'mandatory output items', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('## Before generating', 'From awesome-chatgpt-prompts community collection', 'analyze these sources', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- Source roots per module: `*/src/main/java/`', 'From awesome-chatgpt-prompts community collection', '`*/src/main/kotlin/`', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('Hilt (`@HiltAndroidApp`', 'From awesome-chatgpt-prompts community collection', '`@AndroidEntryPoint`', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `app/src/main/java/`', 'From awesome-chatgpt-prompts community collection', '`app/src/main/kotlin/`', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `app/src/test/`', 'From awesome-chatgpt-prompts community collection', '`app/src/androidTest/`', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('## Before generating', 'From awesome-chatgpt-prompts community collection', 'analyze these sources', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `conanfile.*`', 'From awesome-chatgpt-prompts community collection', '`vcpkg.json` (if present)', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `Directory.Build.props`', 'From awesome-chatgpt-prompts community collection', '`Directory.Build.targets`', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('## Before generating', 'From awesome-chatgpt-prompts community collection', 'analyze these sources', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `*.sln`', 'From awesome-chatgpt-prompts community collection', '`*.csproj` / `*.fsproj` / `*.vbproj`', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `Directory.Build.props`', 'From awesome-chatgpt-prompts community collection', '`Directory.Build.targets`', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `dotnet run`', 'From awesome-chatgpt-prompts community collection', '`dotnet test` usage in docs/scripts', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('## Before generating', 'From awesome-chatgpt-prompts community collection', 'analyze these sources', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('## Before generating', 'From awesome-chatgpt-prompts community collection', 'analyze these sources', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `Dockerfile`', 'From awesome-chatgpt-prompts community collection', '`docker-compose.yml`', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('## Before generating', 'From awesome-chatgpt-prompts community collection', 'analyze these sources', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `Makefile` targets', 'From awesome-chatgpt-prompts community collection', '`Taskfile.yml` tasks', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('## Before generating', 'From awesome-chatgpt-prompts community collection', 'analyze these sources', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `go test ./...`', 'From awesome-chatgpt-prompts community collection', '`go run` usage in docs/scripts', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('## Before generating', 'From awesome-chatgpt-prompts community collection', 'analyze these sources', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `Podfile`', 'From awesome-chatgpt-prompts community collection', '`Cartfile` (if present)', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('`@Environment`', 'From awesome-chatgpt-prompts community collection', '`@EnvironmentObject`', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `src/main/resources/application.yml`', 'From awesome-chatgpt-prompts community collection', '`src/main/resources/application.properties`', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('## Before generating', 'From awesome-chatgpt-prompts community collection', 'analyze these sources', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `./mvnw spring-boot:run`', 'From awesome-chatgpt-prompts community collection', '`./gradlew bootRun` usage in docs/scripts', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `src/main/resources`', 'From awesome-chatgpt-prompts community collection', '`src/test/resources`', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `src/main/java/**/controller`', 'From awesome-chatgpt-prompts community collection', '`src/main/java/**/service`', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('## Before generating', 'From awesome-chatgpt-prompts community collection', 'analyze these sources', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `apps/*/package.json`', 'From awesome-chatgpt-prompts community collection', '`packages/*/package.json` (if monorepo)', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('`svelte.config.*`', 'From awesome-chatgpt-prompts community collection', '`astro.config.*` (if present)', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `apps/`', 'From awesome-chatgpt-prompts community collection', '`packages/` (monorepos)', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `phalcon/ide-stubs`', 'From awesome-chatgpt-prompts community collection', '`phalcon/devtools` (Phalcon)', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `app/Config/Modules.php`', 'From awesome-chatgpt-prompts community collection', '`app/Config/Autoload.php` (CI4)', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('## Before generating', 'From awesome-chatgpt-prompts community collection', 'analyze these sources', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `bin/worker.php`', 'From awesome-chatgpt-prompts community collection', '`bin/console.php` (CLI entry points)', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- For each significant module (>5 files)', 'From awesome-chatgpt-prompts community collection', 'note its purpose if inferable from name', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `app/Services/`', 'From awesome-chatgpt-prompts community collection', '`app/Domains/` - Laravel domain-driven', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `app/Modules/`', 'From awesome-chatgpt-prompts community collection', '`modules/` - Laravel/CI4 HMVC', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- Framework-specific: ServiceProvider (Laravel)', 'From awesome-chatgpt-prompts community collection', 'Module.php (Phalcon/CI4)', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `php artisan`', 'From awesome-chatgpt-prompts community collection', '`bin/console` usage in docs/scripts', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `requirements.txt`', 'From awesome-chatgpt-prompts community collection', '`requirements-dev.txt`', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('## Before generating', 'From awesome-chatgpt-prompts community collection', 'analyze these sources', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `eas.json`', 'From awesome-chatgpt-prompts community collection', '`expo` in `package.json`', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('## Before generating', 'From awesome-chatgpt-prompts community collection', 'analyze these sources', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('## Before generating', 'From awesome-chatgpt-prompts community collection', 'analyze these sources', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `apps/*/package.json`', 'From awesome-chatgpt-prompts community collection', '`packages/*/package.json` (if monorepo)', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('hooks `use*`', 'From awesome-chatgpt-prompts community collection', 'components PascalCase', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `apps/`', 'From awesome-chatgpt-prompts community collection', '`packages/` (monorepos)', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('## Before generating', 'From awesome-chatgpt-prompts community collection', 'analyze these sources', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('`config/routes.rb`', 'From awesome-chatgpt-prompts community collection', '`config/application.rb`', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('`db/migrate`', 'From awesome-chatgpt-prompts community collection', '`ActiveRecord::Base`', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('## Before generating', 'From awesome-chatgpt-prompts community collection', 'analyze these sources', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `cargo test`', 'From awesome-chatgpt-prompts community collection', '`cargo run` usage in docs/scripts', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('description: Discover codebase patterns and auto-generate SKILL files for .claude/skills/. Use when analyzing project for missing skills', 'From awesome-chatgpt-prompts community collection', 'creating new skills from codebase patterns', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- {skill-name}: {pattern}', 'From awesome-chatgpt-prompts community collection', '{file-count} files found', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- Smart merge: preserve custom content', 'From awesome-chatgpt-prompts community collection', 'add missing sections', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- Use backup as source', 'From awesome-chatgpt-prompts community collection', 'extract relevant content', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Android/Gradle | `build.gradle`', 'From awesome-chatgpt-prompts community collection', '`settings.gradle` | `references/android.md` |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| iOS/Xcode | `*.xcodeproj`', 'From awesome-chatgpt-prompts community collection', '`Package.swift` | `references/ios.md` |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Python | `pyproject.toml`', 'From awesome-chatgpt-prompts community collection', '`requirements.txt` | `references/python.md` |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Java/JVM | `pom.xml`', 'From awesome-chatgpt-prompts community collection', '`build.gradle` | `references/java.md` |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| .NET/C# | `*.csproj`', 'From awesome-chatgpt-prompts community collection', '`*.sln` | `references/dotnet.md` |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| C/C++ | `CMakeLists.txt`', 'From awesome-chatgpt-prompts community collection', '`Makefile` | `references/cpp.md` |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('If multiple platforms detected', 'From awesome-chatgpt-prompts community collection', 'read multiple references.', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- Extract: Do/Don''t rules', 'From awesome-chatgpt-prompts community collection', 'architecture constraints', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `gradle.properties`', 'From awesome-chatgpt-prompts community collection', '`gradle/libs.versions.toml`', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `gradlew`', 'From awesome-chatgpt-prompts community collection', '`gradle/wrapper/gradle-wrapper.properties`', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `*/src/main/java/`', 'From awesome-chatgpt-prompts community collection', '`*/src/main/kotlin/`', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Repository | `*Repository`', 'From awesome-chatgpt-prompts community collection', '`*RepositoryImpl` | data-repository |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| UseCase | `operator fun invoke`', 'From awesome-chatgpt-prompts community collection', '`*UseCase` | domain-usecase |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Migration | `Migration(`', 'From awesome-chatgpt-prompts community collection', '`@Database(version=` | room-migration |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Type Converter | `@TypeConverter`', 'From awesome-chatgpt-prompts community collection', '`@TypeConverters` | type-converter |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Compose Screen | `@Composable`', 'From awesome-chatgpt-prompts community collection', '`NavGraphBuilder.` | compose-screen |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Bottom Sheet | `ModalBottomSheet`', 'From awesome-chatgpt-prompts community collection', '`*BottomSheet(` | bottomsheet-screen |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| DataStore | `DataStore<Preferences>`', 'From awesome-chatgpt-prompts community collection', '`preferencesDataStore` | datastore-preference |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Interceptor | `Interceptor`', 'From awesome-chatgpt-prompts community collection', '`intercept()` | network-interceptor |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Broadcast Receiver | `BroadcastReceiver`', 'From awesome-chatgpt-prompts community collection', '`onReceive(` | broadcast-receiver |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Android Service | `: Service()`', 'From awesome-chatgpt-prompts community collection', '`ForegroundService` | android-service |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Notification | `NotificationCompat`', 'From awesome-chatgpt-prompts community collection', '`NotificationChannel` | notification-builder |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Analytics | `FirebaseAnalytics`', 'From awesome-chatgpt-prompts community collection', '`logEvent` | analytics-event |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Feature Flag | `RemoteConfig`', 'From awesome-chatgpt-prompts community collection', '`FeatureFlag` | feature-flag |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| App Widget | `AppWidgetProvider`', 'From awesome-chatgpt-prompts community collection', '`GlanceAppWidget` | app-widget |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `app/src/main/java/`', 'From awesome-chatgpt-prompts community collection', '`app/src/main/kotlin/`', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `app/src/test/`', 'From awesome-chatgpt-prompts community collection', '`app/src/androidTest/`', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `conanfile.txt`', 'From awesome-chatgpt-prompts community collection', '`conanfile.py` (Conan)', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Template | `template<`', 'From awesome-chatgpt-prompts community collection', '`typename T` | cpp-template |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Smart Pointer | `std::unique_ptr`', 'From awesome-chatgpt-prompts community collection', '`std::shared_ptr` | smart-pointer |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| RAII | destructor pattern', 'From awesome-chatgpt-prompts community collection', '`~*()` | raii-pattern |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Factory | `create*()`', 'From awesome-chatgpt-prompts community collection', '`make*()` | factory-pattern |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Mutex | `std::mutex`', 'From awesome-chatgpt-prompts community collection', '`std::lock_guard` | synchronization |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Serialization | `nlohmann::json`', 'From awesome-chatgpt-prompts community collection', '`protobuf` | serialization |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Catch2 Test | `TEST_CASE(`', 'From awesome-chatgpt-prompts community collection', '`REQUIRE(` | catch2-test |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `src/`', 'From awesome-chatgpt-prompts community collection', '`tests/` directories with projects', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Service | `I*Service`', 'From awesome-chatgpt-prompts community collection', '`class *Service` | dotnet-service |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Repository | `I*Repository`', 'From awesome-chatgpt-prompts community collection', '`class *Repository` | dotnet-repository |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| DbContext | `: DbContext`', 'From awesome-chatgpt-prompts community collection', '`DbSet<` | ef-dbcontext |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Middleware | `IMiddleware`', 'From awesome-chatgpt-prompts community collection', '`RequestDelegate` | aspnet-middleware |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Background Service | `BackgroundService`', 'From awesome-chatgpt-prompts community collection', '`IHostedService` | background-service |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| MediatR Handler | `IRequestHandler<`', 'From awesome-chatgpt-prompts community collection', '`INotificationHandler<` | mediatr-handler |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| SignalR Hub | `: Hub`', 'From awesome-chatgpt-prompts community collection', '`[HubName]` | signalr-hub |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Minimal API | `app.MapGet(`', 'From awesome-chatgpt-prompts community collection', '`app.MapPost(` | minimal-api |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| gRPC Service | `*.proto`', 'From awesome-chatgpt-prompts community collection', '`: *Base` | grpc-service |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| EF Migration | `Migrations/`', 'From awesome-chatgpt-prompts community collection', '`AddMigration` | ef-migration |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Integration Test | `WebApplicationFactory`', 'From awesome-chatgpt-prompts community collection', '`IClassFixture` | integration-test |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Ecto Schema | `use Ecto.Schema`', 'From awesome-chatgpt-prompts community collection', '`schema ""` | ecto-schema |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Ecto Migration | `use Ecto.Migration`', 'From awesome-chatgpt-prompts community collection', '`create table` | ecto-migration |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Ecto Changeset | `cast/4`', 'From awesome-chatgpt-prompts community collection', '`validate_required` | ecto-changeset |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Context | `defmodule *Context`', 'From awesome-chatgpt-prompts community collection', '`def list_*` | phoenix-context |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| GenServer | `use GenServer`', 'From awesome-chatgpt-prompts community collection', '`handle_call` | genserver |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Supervisor | `use Supervisor`', 'From awesome-chatgpt-prompts community collection', '`start_link` | supervisor |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Task | `Task.async`', 'From awesome-chatgpt-prompts community collection', '`Task.Supervisor` | elixir-task |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Oban Worker | `use Oban.Worker`', 'From awesome-chatgpt-prompts community collection', '`perform/1` | oban-worker |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Absinthe | `use Absinthe.Schema`', 'From awesome-chatgpt-prompts community collection', '`field :` | graphql-schema |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| ExUnit Test | `use ExUnit.Case`', 'From awesome-chatgpt-prompts community collection', '`test ""` | exunit-test |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Widget | `extends StatelessWidget`', 'From awesome-chatgpt-prompts community collection', '`extends StatefulWidget` | flutter-widget |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| BLoC | `extends Bloc<`', 'From awesome-chatgpt-prompts community collection', '`extends Cubit<` | bloc-pattern |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Repository | `*Repository`', 'From awesome-chatgpt-prompts community collection', '`abstract class *Repository` | data-repository |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Freezed | `@freezed`', 'From awesome-chatgpt-prompts community collection', '`part ''*.freezed.dart''` | freezed-model |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Integration Test | `integration_test`', 'From awesome-chatgpt-prompts community collection', '`IntegrationTestWidgetsFlutterBinding` | integration-test |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Config | `config.*`', 'From awesome-chatgpt-prompts community collection', '`settings.*` | config-file |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Service | `service/`', 'From awesome-chatgpt-prompts community collection', 'business logic | service-layer |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Script | `scripts/`', 'From awesome-chatgpt-prompts community collection', '`bin/` | script-file |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Documentation | `docs/`', 'From awesome-chatgpt-prompts community collection', '`*.md` | documentation |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| gRPC Service | `*.proto`', 'From awesome-chatgpt-prompts community collection', '`pb.*Server` | grpc-service |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Repository | `type *Repository interface`', 'From awesome-chatgpt-prompts community collection', '`*Repository` | data-repository |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Service | `type *Service interface`', 'From awesome-chatgpt-prompts community collection', '`*Service` | service-layer |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| GORM Model | `gorm.Model`', 'From awesome-chatgpt-prompts community collection', '`*gorm.DB` | gorm-model |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| sqlx | `sqlx.DB`', 'From awesome-chatgpt-prompts community collection', '`sqlx.NamedExec` | sqlx-usage |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Migration | `goose`', 'From awesome-chatgpt-prompts community collection', '`golang-migrate` | db-migration |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Middleware | `func(*Context)`', 'From awesome-chatgpt-prompts community collection', '`middleware.*` | go-middleware |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Unit Test | `*_test.go`', 'From awesome-chatgpt-prompts community collection', '`func Test*(t *testing.T)` | go-test |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Mock | `mockgen`', 'From awesome-chatgpt-prompts community collection', '`*_mock.go` | go-mock |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `Podfile`', 'From awesome-chatgpt-prompts community collection', '`Podfile.lock` (CocoaPods)', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| SwiftUI View | `struct *: View`', 'From awesome-chatgpt-prompts community collection', '`var body: some View` | swiftui-view |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| UIKit VC | `UIViewController`', 'From awesome-chatgpt-prompts community collection', '`viewDidLoad()` | uikit-viewcontroller |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Coordinator | `Coordinator`', 'From awesome-chatgpt-prompts community collection', '`*Coordinator` | coordinator-pattern |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Repository | `*Repository`', 'From awesome-chatgpt-prompts community collection', '`protocol *Repository` | data-repository |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Service | `*Service`', 'From awesome-chatgpt-prompts community collection', '`protocol *Service` | service-layer |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Realm | `Object`', 'From awesome-chatgpt-prompts community collection', '`@Persisted` | realm-model |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Navigation | `NavigationStack`', 'From awesome-chatgpt-prompts community collection', '`NavigationPath` | navigation-swiftui |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Unit Test | `XCTestCase`', 'From awesome-chatgpt-prompts community collection', '`func test*()` | xctest |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| UI Test | `XCUIApplication`', 'From awesome-chatgpt-prompts community collection', '`XCUIElement` | xcuitest |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `build.gradle`', 'From awesome-chatgpt-prompts community collection', '`build.gradle.kts` (Gradle)', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `modules/`', 'From awesome-chatgpt-prompts community collection', '`services/` directories', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Service | `@Service`', 'From awesome-chatgpt-prompts community collection', '`class *Service` | spring-service |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Config | `@Configuration`', 'From awesome-chatgpt-prompts community collection', '`@Bean` | spring-config |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Component | `@Component`', 'From awesome-chatgpt-prompts community collection', '`@Autowired` | spring-component |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Security | `@EnableWebSecurity`', 'From awesome-chatgpt-prompts community collection', '`SecurityFilterChain` | spring-security |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Exception Handler | `@ControllerAdvice`', 'From awesome-chatgpt-prompts community collection', '`@ExceptionHandler` | exception-handler |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Scheduler | `@Scheduled`', 'From awesome-chatgpt-prompts community collection', '`@EnableScheduling` | scheduled-task |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Event | `ApplicationEvent`', 'From awesome-chatgpt-prompts community collection', '`@EventListener` | event-listener |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Flyway Migration | `V*__*.sql`', 'From awesome-chatgpt-prompts community collection', '`flyway` | flyway-migration |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Liquibase | `changelog*.xml`', 'From awesome-chatgpt-prompts community collection', '`liquibase` | liquibase-migration |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Integration Test | `@DataJpaTest`', 'From awesome-chatgpt-prompts community collection', '`@WebMvcTest` | integration-test |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `pom.xml` plugins', 'From awesome-chatgpt-prompts community collection', '`build.gradle` tasks', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| NestJS Service | `@Injectable`', 'From awesome-chatgpt-prompts community collection', '`@Service` | nestjs-service |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Fastify Route | `fastify.get(`', 'From awesome-chatgpt-prompts community collection', '`fastify.post(` | fastify-route |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Prisma Model | `prisma.*.create`', 'From awesome-chatgpt-prompts community collection', '`prisma.*.findMany` | prisma-usage |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Mongoose Model | `mongoose.Schema`', 'From awesome-chatgpt-prompts community collection', '`mongoose.model(` | mongoose-model |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Sequelize Model | `Model.init`', 'From awesome-chatgpt-prompts community collection', '`DataTypes` | sequelize-model |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| E2E Test | `supertest`', 'From awesome-chatgpt-prompts community collection', '`request(app)` | e2e-test |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `app/Config/Routes.php`', 'From awesome-chatgpt-prompts community collection', '`app/Database/Migrations`', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Laravel Controller | `extends Controller`', 'From awesome-chatgpt-prompts community collection', '`public function index` | laravel-controller |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Laravel Model | `extends Model`', 'From awesome-chatgpt-prompts community collection', '`protected $fillable` | laravel-model |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Laravel Migration | `extends Migration`', 'From awesome-chatgpt-prompts community collection', '`Schema::create` | laravel-migration |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Laravel Service | `class *Service`', 'From awesome-chatgpt-prompts community collection', '`app/Services/` | laravel-service |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Laravel Repository | `*Repository`', 'From awesome-chatgpt-prompts community collection', '`interface *Repository` | laravel-repository |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Laravel Job | `implements ShouldQueue`', 'From awesome-chatgpt-prompts community collection', '`dispatch(` | laravel-job |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Laravel Event | `extends Event`', 'From awesome-chatgpt-prompts community collection', '`event(` | laravel-event |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Symfony Controller | `#[Route]`', 'From awesome-chatgpt-prompts community collection', '`AbstractController` | symfony-controller |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Symfony Service | `#[AsService]`', 'From awesome-chatgpt-prompts community collection', '`services.yaml` | symfony-service |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Doctrine Entity | `#[ORM\Entity]`', 'From awesome-chatgpt-prompts community collection', '`#[ORM\Column]` | doctrine-entity |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Doctrine Migration | `AbstractMigration`', 'From awesome-chatgpt-prompts community collection', '`$this->addSql` | doctrine-migration |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| CI4 Controller | `extends BaseController`', 'From awesome-chatgpt-prompts community collection', '`app/Controllers/` | ci4-controller |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| CI4 Model | `extends Model`', 'From awesome-chatgpt-prompts community collection', '`protected $table` | ci4-model |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| CI4 Migration | `extends Migration`', 'From awesome-chatgpt-prompts community collection', '`$this->forge->` | ci4-migration |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| CI4 Entity | `extends Entity`', 'From awesome-chatgpt-prompts community collection', '`app/Entities/` | ci4-entity |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Phalcon Controller | `extends Controller`', 'From awesome-chatgpt-prompts community collection', '`Phalcon\Mvc\Controller` | phalcon-controller |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Phalcon Model | `extends Model`', 'From awesome-chatgpt-prompts community collection', '`Phalcon\Mvc\Model` | phalcon-model |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Phalcon Migration | `Phalcon\Migrations`', 'From awesome-chatgpt-prompts community collection', '`morphTable` | phalcon-migration |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| API Resource | `extends JsonResource`', 'From awesome-chatgpt-prompts community collection', '`toArray` | api-resource |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Form Request | `extends FormRequest`', 'From awesome-chatgpt-prompts community collection', '`rules()` | form-request |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Middleware | `implements Middleware`', 'From awesome-chatgpt-prompts community collection', '`handle(` | php-middleware |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `requirements.txt`', 'From awesome-chatgpt-prompts community collection', '`requirements-dev.txt`', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('- `manage.py`', 'From awesome-chatgpt-prompts community collection', '`settings.py` (Django)', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| FastAPI Dependency | `Depends(`', 'From awesome-chatgpt-prompts community collection', '`def get_*():` | fastapi-dependency |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Django Model | `models.Model`', 'From awesome-chatgpt-prompts community collection', '`class Meta:` | django-model |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Django Serializer | `serializers.Serializer`', 'From awesome-chatgpt-prompts community collection', '`ModelSerializer` | drf-serializer |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Flask Route | `@app.route`', 'From awesome-chatgpt-prompts community collection', '`Blueprint` | flask-route |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Alembic Migration | `alembic/versions/`', 'From awesome-chatgpt-prompts community collection', '`op.create_table` | alembic-migration |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Repository | `*Repository`', 'From awesome-chatgpt-prompts community collection', '`class *Repository` | data-repository |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Service | `*Service`', 'From awesome-chatgpt-prompts community collection', '`class *Service` | service-layer |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use'),
('| Celery Task | `@celery.task`', 'From awesome-chatgpt-prompts community collection', '`@shared_task` | celery-task |', 'chatgpt', 1, ARRAY['community', 'chatgpt', 'prompts'], 'General use');